name:                bujo
version:             0.1.0.0
github:              "githubuser/sfpl-gopher"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sfpl-gopher#readme>

dependencies:
- base

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - DeriveAnyClass
  - OverloadedRecordDot
  - DuplicateRecordFields
  default-language: GHC2021
  dependencies:
  - Venusia
  - containers
  - filepath
  - directory
  - time
  - unordered-containers
  - bytestring
  - network
  - text
  - aeson
  - yaml

executables:
  bujo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - OverloadedStrings
    - DeriveGeneric
    - DeriveAnyClass
    - OverloadedRecordDot
    - DuplicateRecordFields
    default-language: GHC2021
    dependencies:
    - Venusia
    - bujo
    - containers
    - filepath
    - directory
    - time
    - unordered-containers
    - bytestring
    - network

tests:
  bujo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bujo
